### ISSUE TITLE
0042 号リリースまでの TODO

### ISSUE THREAD

**Issue by sunaot** [rubima/rubima#159]
個別に issue にしてもいいのだけど忘れる前に書いておきます。
- [x] 分野別目次の更新
- [x] 各号目次の更新
- [x] 巻頭言の記事紹介の更新
- [x] 表紙の Regional report の採番
- [x] ぐんま01の文章が消えてしまってる件の fix (他にないかもチェックしたいかも)
- [x] Turnip の残りの校正
- [x] 福岡01の写真
- [x] jp.rubyist.net/magazine に 0042 号へのリンクを追加 (リリース後)

他、気づいたものあればコメントください。上記のリストにマージします。
